### ISSUE TITLE
On each cycle agent has to get new contents of available_commands.sh

### ISSUE THREAD

**Issue by liesislukas** [Trafikito/agent#3]
Now if the agent is running, it has contents of available_commands.sh in memory so if I edit a file, there is no change for the agent. It needs to be restarted. The agent has always "see" 
- new commands
- command updates
at available_commands.sh

if the file is not available - agent should stop. So during uninstallation, it will be enough to simply remove the files

**Comment by pgpleroux** [comment]
I am changing the agent to run with systemd, this eliminates the cron deps + multiple runs.
In practice this means that you need to restart the agent with
systemctl restart trafikito.service
This should solve the problem...

**Comment by pgpleroux** [comment]
Added an agent wrapper that starts the agent in a new shell - this solves the problem of changing configuration while the agent is running.
