### ISSUE TITLE
Current requirements

### ISSUE THREAD

**Issue by liesislukas** [Trafikito/agent#4]
If haven't missed anything, these are the requirements from env:

```
CURL with SSL, sh, crontab, grep, sed, awk, head, eval, touch, chmod
```

Can we make this list shorter?
Do you see any other requirements?

**Comment by pgpleroux** [comment]
Most of these commands are as defined in the POSIX standard for Linux and will be available on any distro that I have ever used.
Just in case, the new install script will try to install missing commands that may not be present in a minimal install.
