### ISSUE TITLE
Is agent POSIX compliant?

### ISSUE THREAD

**Issue by liesislukas** [Trafikito/agent#5]
If not, what can be done? Do you think it is needed to be POSIX compliant to run on most machines?

Trafikito agent should be able to run on devices like drones, robotic vacuum cleaners and basically anything that has any flavor of Linux and ability to run shells script. So it could truly monitor anything and take automatic action when something.

**Comment by pgpleroux** [comment]
POSIX compliant makes sense, but some people as different ideas - bash is NOT compliant, but as lomg as you stick to the POSIX shell things should be okay.
The way you define the hash bang as '#!/usr/bin/env sh' is a good start for probably most Unix/Linux distros, but it points to different commands, eg:
Debian9 - /bin/dash (with a 'd' = POSIX)
Centos7 - /bin/bash
Ubuntu17 - /bin/dash
I will check for bash specific code in scripts.

**Comment by pgpleroux** [comment]
Yes - the code is now POSIX compliant
